import AppBar from './components/AppBar.vue';
import Accordion from './components/Accordion.vue';
import AccordionItem from './components/AccordionItem.vue';
import AccordionItemHeader from './components/AccordionItemHeader.vue';
import AccordionItemContent from './components/AccordionItemContent.vue';
import ScrollBar from './components/ScrollBar.vue';
import Avatar from './components/Avatar.vue';
import Cards from './components/Cards.vue';
import CardsAction from './components/CardsAction.vue';
import CardsContent from './components/CardsContent.vue';
import CardsContentScrollbar from './components/CardsContentScrollbar.vue';
import CardsHeader from './components/CardsHeader.vue';
import CardsImage from './components/CardsImage.vue';
import CardsSlider from './components/CardsSlider.vue';
import CardsSliderItem from './components/CardsSliderItem.vue';
import Chart from './components/Chart.vue';
import Clearfix from './components/Clearfix.vue';
import ColorButton from './components/ColorButton.vue';
import ConfirmationDialog from './components/ConfirmationDialog.vue';
import Checkbox from './components/Checkbox.vue';
import DataTable from './components/DataTable.vue';
import Divider from './components/Divider.vue';
import DropdownMenu from './components/DropdownMenu.vue';
import DropdownSelect from './components/DropdownSelect.vue';
import MenuContent from './components/MenuContent.vue';
import MenuItem from './components/MenuItem.vue';
import MenuOption from './components/MenuOption.vue';
import FlatButton from './components/FlatButton.vue';
import IconButton from './components/IconButton.vue';
import Icon from './components/Icon.vue';
import ImageSlider from './components/ImageSlider.vue';
import ImageSliderItem from './components/ImageSliderItem.vue';
import List from './components/List.vue';
import ListItem from './components/ListItem.vue';
import LoadImg from './components/LoadImg.vue';
import Modal from './components/Modal.vue';
import NavList from './components/NavList.vue';
import PageContainer from './components/PageContainer.vue';
import Radio from './components/Radio.vue';
import RaisedButton from './components/RaisedButton.vue';
import Reveal from './components/Reveal.vue';
import SearchBox from './components/SearchBox.vue';
import SideNavigation from './components/SideNavigation.vue';
import Slider from './components/Slider.vue';
import SliderItem from './components/SliderItem.vue';
import Switches from './components/Switches.vue';
import Tab from './components/Tab.vue';
import TabContent from './components/TabContent.vue';
import TabContentItem from './components/TabContentItem.vue';
import TabItem from './components/TabItem.vue';
import Textfield from './components/Textfield.vue';
import Tooltip from './components/Tooltip.vue';
import TransitionBlock from './components/TransitionBlock.vue';
import RangeSlider from './components/RangeSlider.vue';

export default {
    install(vmVue) {
        vmVue.component("scroll-bar", ScrollBar);
        vmVue.component("app-bar", AppBar);
        vmVue.component("accordion", Accordion);
        vmVue.component("accordion-item", AccordionItem);
        vmVue.component("accordion-item-header", AccordionItemHeader);
        vmVue.component("accordion-item-content", AccordionItemContent);
        vmVue.component("avatar", Avatar);
        vmVue.component("cards", Cards);
        vmVue.component("cards-action", CardsAction);
        vmVue.component("cards-content", CardsContent);
        vmVue.component("cards-content-scrollbar", CardsContentScrollbar);
        vmVue.component("cards-header", CardsHeader);
        vmVue.component("cards-image", CardsImage);
        vmVue.component("cards-slider", CardsSlider);
        vmVue.component("cards-slider-item", CardsSliderItem);
        vmVue.component("chart", Chart);
        vmVue.component("clearfix", Clearfix);
        vmVue.component("color-button", ColorButton);
        vmVue.component("confirmation-dialog", ConfirmationDialog);
        vmVue.component("checkbox", Checkbox);
        vmVue.component("data-table", DataTable);
        vmVue.component("divider", Divider);
        vmVue.component("dropdown-menu", DropdownMenu);
        vmVue.component("dropdown-select", DropdownSelect);
        vmVue.component("flat-button", FlatButton);
        vmVue.component("icon", Icon);
        vmVue.component("icon-button", IconButton);
        vmVue.component("image-slider", ImageSlider);
        vmVue.component("image-slider-item", ImageSliderItem);
        vmVue.component("list", List);
        vmVue.component("list-item", ListItem);
        vmVue.component("load-img", LoadImg);
        vmVue.component("menu-content", MenuContent);
        vmVue.component("menu-item", MenuItem);
        vmVue.component("menu-option", MenuOption);
        vmVue.component("modal", Modal);
        vmVue.component("nav-list", NavList);
        vmVue.component("page-container", PageContainer);
        vmVue.component("radio", Radio);
        vmVue.component("raised-button", RaisedButton);
        vmVue.component("range-slider", RangeSlider);
        vmVue.component("reveal", Reveal);
        vmVue.component("search-box", SearchBox);
        vmVue.component("side-navigation", SideNavigation);
        vmVue.component("slider", Slider);
        vmVue.component("slider-item", SliderItem);
        vmVue.component("switches", Switches);
        vmVue.component("tab", Tab);
        vmVue.component("tab-content", TabContent);
        vmVue.component("tab-content-item", TabContentItem);
        vmVue.component("tab-item", TabItem);
        vmVue.component("textfield", Textfield);
        vmVue.component("tooltip", Tooltip);
        vmVue.component("transition-block", TransitionBlock);
    }
};