import AppBar from './components/AppBar.vue';
import Accordion from './components/Accordion.vue';
import AccordionItem from './components/AccordionItem.vue';
import AccordionItemHeader from './components/AccordionItemHeader.vue';
import AccordionItemContent from './components/AccordionItemContent.vue';
import ScrollBar from './components/ScrollBar.vue';
import Avatar from './components/Avatar.vue';
import Cards from './components/Cards.vue';
import CardsAction from './components/CardsAction.vue';
import CardsContent from './components/CardsContent.vue';
import CardsHeader from './components/CardsHeader.vue';
import CardsImage from './components/CardsImage.vue';
import Chart from './components/Chart.vue';
import Clearfix from './components/Clearfix.vue';
import ColorButton from './components/ColorButton.vue';
import ConfirmationDialog from './components/ConfirmationDialog.vue';
import Checkbox from './components/Checkbox.vue';
import DataTable from './components/DataTable.vue';
import Divider from './components/Divider.vue';
import DropdownMenu from './components/DropdownMenu.vue';
import DropdownSelect from './components/DropdownSelect.vue';
import MenuContent from './components/MenuContent.vue';
import MenuItem from './components/MenuItem.vue';
import MenuOption from './components/MenuOption.vue';
import FlatButton from './components/FlatButton.vue';
import IconButton from './components/IconButton.vue';
import Icon from './components/Icon.vue';
import LoadImg from './components/LoadImg.vue';
import Modal from './components/Modal.vue';
import NavList from './components/NavList.vue';
import PageContainer from './components/PageContainer.vue';
import Radio from './components/Radio.vue';
import RaisedButton from './components/RaisedButton.vue';
import Reveal from './components/Reveal.vue';
import SearchBox from './components/SearchBox.vue';
import SideNavigation from './components/SideNavigation.vue';
import Switches from './components/Switches.vue';
import Tab from './components/Tab.vue';
import TabContent from './components/TabContent.vue';
import TabContentItem from './components/TabContentItem.vue';
import TabItem from './components/TabItem.vue';
import Textfield from './components/Textfield.vue';
import Tooltip from './components/Tooltip.vue';
import TransitionBlock from './components/TransitionBlock.vue';
import Sugar from 'sugar';


Sugar.extend();
Vue.component("scroll-bar", ScrollBar);
Vue.component("app-bar", AppBar);
Vue.component("accordion", Accordion);
Vue.component("accordion-item", AccordionItem);
Vue.component("accordion-item-header", AccordionItemHeader);
Vue.component("accordion-item-content", AccordionItemContent);
Vue.component("avatar", Avatar);
Vue.component("cards", Cards);
Vue.component("cards-action", CardsAction);
Vue.component("cards-content", CardsContent);
Vue.component("cards-header", CardsHeader);
Vue.component("cards-image", CardsImage);
Vue.component("chart", Chart);
Vue.component("clearfix", Clearfix);
Vue.component("color-button", ColorButton);
Vue.component("confirmation-dialog", ConfirmationDialog);
Vue.component("checkbox", Checkbox);
Vue.component("data-table", DataTable);
Vue.component("divider", Divider);
Vue.component("dropdown-menu", DropdownMenu);
Vue.component("dropdown-select", DropdownSelect);
Vue.component("flat-button", FlatButton);
Vue.component("icon", Icon);
Vue.component("icon-button", IconButton);
Vue.component("load-img", LoadImg);
Vue.component("menu-content", MenuContent);
Vue.component("menu-item", MenuItem);
Vue.component("menu-option", MenuOption);
Vue.component("modal", Modal);
Vue.component("nav-list", NavList);
Vue.component("page-container", PageContainer);
Vue.component("radio", Radio);
Vue.component("raised-button", RaisedButton);
Vue.component("reveal", Reveal);
Vue.component("search-box", SearchBox);
Vue.component("side-navigation", SideNavigation);
Vue.component("switches", Switches);
Vue.component("tab", Tab);
Vue.component("tab-content", TabContent);
Vue.component("tab-content-item", TabContentItem);
Vue.component("tab-item", TabItem);
Vue.component("textfield", Textfield);
Vue.component("tooltip", Tooltip);
Vue.component("transition-block", TransitionBlock);